#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»
# EMU=«path-to-x16-emulator»
# TGT=«target»
# EXT=«target-executable-extension»
# OUT=«target-filename-case-upper-or-lower»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT
EMU=~/Documents/development/x16emu_linux-x86_64-r49
TGT=cx16
EXT=prg
OUT=upper

xform() {
    local x="$1"

    if [[ $OUT == upper ]]; then
        echo "${x^^}"
    else
        echo "${x,,}"
    fi
}

# Build data
C=data
php $FLT/flt/flt.php -i $C.c -o $C-flt.c -x "-I $XCC/include -I $FLT/flt"
$XCC/bin/cc65 -t $TGT -I $XCC/include $C-flt.c
$XCC/bin/ca65 -t $TGT $C-flt.s
$XCC/bin/ld65 -o $(xform $C.$EXT) -t $TGT $C-flt.o -L $FLT/flt flt-$TGT.lib -L $XCC/lib $TGT.lib

# Build explore
for C in main initialize xm $TGT-specific process-vehicles scan-field render-objects
do
	$XCC/bin/cc65 -t $TGT -Cl -Oir -I $XCC/include $C.c
	$XCC/bin/ca65 -t $TGT $C.s
done
C=explore
$XCC/bin/ld65 -o $(xform $C.$EXT) -t $TGT main.o initialize.o xm.o $TGT-specific.o process-vehicles.o scan-field.o render-objects.o -L $XCC/lib $TGT.lib

# Move to the emulator
for C in data explore
do
	mv $(xform $C.$EXT) $EMU/
done

# Clean up
rm *-flt.c *.s *.o

# Run the emulator
cd $EMU
./x16emu -scale 2 -mhz 8
#./x16emu -scale 2 -warp -prg $(xform data.$EXT) -run
#./x16emu -scale 2 -mhz 8 -prg $(xform explore.$EXT) -run
