#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»/flt
# EMU=«path-to-x16-emulator»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT/flt
EMU=~/Documents/development/x16emu_linux-x86_64-r46

# Build data.prg
php $FLT/flt.php -i data.c -o data-flt.c -x "-I $XCC/include -I $FLT"
$XCC/bin/cc65 -t cx16 -I $XCC/include data-flt.c
$XCC/bin/ca65 -t cx16 data-flt.s
$XCC/bin/ld65 -o data.prg -t cx16 data-flt.o -L $FLT flt.lib -L $XCC/lib cx16.lib

# Build explore.prg
for C in main initialize xm cx16-specific process-vehicles scan-field render-objects
do
	$XCC/bin/cc65 -t cx16 -Cl -Oir -I $XCC/include $C.c
	$XCC/bin/ca65 -t cx16 $C.s
done
$XCC/bin/ld65 -o explore.prg -t cx16 main.o initialize.o xm.o cx16-specific.o process-vehicles.o scan-field.o render-objects.o -L $XCC/lib cx16.lib

# Move to the emulator
mv data.prg explore.prg $EMU/

# Clean up
rm *-flt.c *.s *.o

# Run the emulator
cd $EMU
# ./x16emu -scale 2 -mhz 8
# ./x16emu -scale 2 -warp -prg data.prg -run
./x16emu -scale 2 -mhz 8 -prg explore.prg -run
