;
; File generated by cc65 v 2.19 - Git 39619b629
;
	.fopt		compiler,"cc65 v 2.19 - Git 39619b629"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clock
	.import		_OutputAsNumber
	.import		_ExitProgram
	.import		_InitProgram
	.import		_ProcessVehicles
	.import		_RenderObjects
	.import		_UpdateDisplay
	.import		_g_exit_program
	.import		_g_frame_counter
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _InitProgram
	jsr     _clock
	jsr     negeax
	sta     M0001
	stx     M0001+1
	ldy     sreg
	sty     M0001+2
	ldy     sreg+1
	sty     M0001+3
	bra     L0004
L0002:	jsr     _ProcessVehicles
	jsr     _RenderObjects
	jsr     _UpdateDisplay
	inc     _g_frame_counter
	bne     L0004
	inc     _g_frame_counter+1
L0004:	lda     _g_exit_program
	beq     L0002
	jsr     _clock
	ldy     #<(M0001)
	sty     ptr1
	ldy     #>(M0001)
	jsr     laddeq
	lda     #$D4
	jsr     pusha
	lda     M0001
	ldx     M0001+1
	jsr     _OutputAsNumber
	lda     #$2F
	jsr     pusha
	lda     _g_frame_counter
	ldx     _g_frame_counter+1
	jsr     _OutputAsNumber
	lda     #$2F
	jsr     pusha
	ldx     #$00
	lda     #$3C
	jsr     _OutputAsNumber
	ldx     #$00
	lda     #$06
	jmp     _ExitProgram

.segment	"BSS"

M0001:
	.res	4,$00

.endproc

