;
; File generated by cc65 v 2.19 - Git 39619b629
;
	.fopt		compiler,"cc65 v 2.19 - Git 39619b629"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.import		_abs
	.import		_GetXMAddress
	.export		_ProcessVehicles
	.import		_GetPlayerInput
	.import		_AddSound
	.import		_AdvancePlayer
	.import		_Minimum
	.import		_Maximum
	.import		_Sin
	.import		_Cos
	.import		_g_arena_data
	.import		_g_exploding_prm
	.import		_g_exploding_aux
	.import		_g_vehicles
	.import		_g_squares
	.import		_g_arena_index

; ---------------------------------------------------------------
; void __near__ ProcessVehicles (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ProcessVehicles: near

.segment	"CODE"

	lda     _g_arena_data
	ldx     _g_arena_data+1
	jsr     pushax
	lda     _g_arena_index
	ldx     _g_arena_index+1
	jsr     _GetXMAddress
	sta     M0004
	stx     M0004+1
	stz     M0005
	stz     M0005+1
	lda     _g_vehicles+1
	sta     M0001+1
	lda     _g_vehicles
	sta     M0001
L0002:	lda     M0005
	cmp     #$04
	lda     M0005+1
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	jpl     L0003
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     (ptr1)
	jeq     L0004
	lda     M0005
	ora     M0005+1
	bne     L000A
	lda     M0001
	ldx     M0001+1
	jsr     _GetPlayerInput
L000A:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     sreg
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L000C
	dex
L000C:	jsr     asrax2
	clc
	adc     sreg
	bcc     L006D
	inx
L006D:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     M0009+1
	lda     (ptr1)
	sta     M0009
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$16
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	cmp     M0009
	txa
	sbc     M0009+1
	bvc     L006E
	eor     #$80
L006E:	bmi     L007D
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	bne     L000D
L007D:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     M0009
	ldy     #$15
	sta     (ptr1),y
	iny
	lda     M0009+1
	sta     (ptr1),y
L000D:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$12
	lda     (ptr1),y
	sta     M0007+1
	dey
	lda     (ptr1),y
	sta     M0007
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	sta     M0008+1
	dey
	lda     (ptr1),y
	sta     M0008
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$16
	lda     (ptr1),y
	sta     M0009+1
	dey
	lda     (ptr1),y
	sta     M0009
	lda     M0001
	ldx     M0001+1
	ldy     #$05
	jsr     ldaidx
	jeq     L0010
	lda     M0001
	ldx     M0001+1
	sta     ptr2
	stx     ptr2+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$18
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     sreg
	stx     sreg+1
	lda     M0001
	ldx     M0001+1
	ldy     #$05
	jsr     ldaidx
	jsr     aslax2
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	ldy     #$17
	sta     (ptr2),y
	iny
	txa
	sta     (ptr2),y
	lda     M0001
	ldx     M0001+1
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$18
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _Sin
	ldy     #$19
	jsr     staxspidx
	lda     M0001
	ldx     M0001+1
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$18
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _Cos
	ldy     #$1B
	jsr     staxspidx
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     #$00
	ldy     #$05
	sta     (ptr1),y
L0010:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	beq     L0011
	lda     #$06
	jmp     L00B6
L0011:	lda     M0001
	ldx     M0001+1
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	ldy     #$07
	jsr     ldaidx
	jsr     pushax
	ldx     #$FF
	txa
	jsr     _Maximum
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     _Minimum
	cmp     #$80
	ldy     #$07
	jsr     staspidx
	lda     M0001
	ldx     M0001+1
	ldy     #$07
	jsr     ldaidx
	cmp     #$00
	jeq     L0018
	cmp     #$FF
	bne     L001B
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$1A
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax3
	eor     #$FF
	sec
	adc     M0007
	sta     M0007
	txa
	eor     #$FF
	adc     M0007+1
	sta     M0007+1
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$1C
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax3
	eor     #$FF
	sec
	adc     M0008
	sta     M0008
	txa
	eor     #$FF
	bra     L0086
L001B:	tya
L00B6:	jsr     pusha0
	lda     M0001
	ldx     M0001+1
	ldy     #$07
	jsr     ldaidx
	jsr     tossubax
	cmp     #$80
	sta     M0003
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$1A
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldy     M0003
	lda     ptr1
	ldx     ptr1+1
	jsr     asraxy
	clc
	adc     M0007
	sta     M0007
	txa
	adc     M0007+1
	sta     M0007+1
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$1C
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldy     M0003
	lda     ptr1
	ldx     ptr1+1
	jsr     asraxy
	clc
	adc     M0008
	sta     M0008
	txa
L0086:	adc     M0008+1
	sta     M0008+1
L0018:	lda     M0007
	ldx     M0007+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     _Maximum
	jsr     pushax
	ldx     #$3F
	lda     #$FF
	jsr     _Minimum
	sta     M0007
	stx     M0007+1
	lda     M0008
	ldx     M0008+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     _Maximum
	jsr     pushax
	ldx     #$3F
	lda     #$FF
	jsr     _Minimum
	sta     M0008
	stx     M0008+1
	lda     M0001
	ldx     M0001+1
	ldy     #$04
	jsr     ldaidx
	beq     L001F
	lda     M0001
	ldx     M0001+1
	jsr     ldaidx
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0009
	sta     M0009
	lda     tmp1
	adc     M0009+1
	sta     M0009+1
	lda     M0009
	ldx     M0009+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     _Maximum
	jsr     pushax
	ldx     #$3F
	lda     #$FF
	jsr     _Minimum
	sta     M0009
	stx     M0009+1
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
L001F:	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0008
	ldx     M0008+1
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     ptr1
	ldx     #$00
	lda     M0007+1
	bpl     L0021
	dex
L0021:	jsr     asrax2
	clc
	adc     ptr1
	bcc     L006F
	inx
L006F:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L0020
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     M0007
	ldy     #$11
	sta     (ptr1),y
	iny
	lda     M0007+1
	sta     (ptr1),y
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     M0008
	iny
	sta     (ptr1),y
	iny
	lda     M0008+1
	jmp     L0084
L0020:	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0008
	ldx     M0008+1
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     sreg
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$12
	lda     (ptr1),y
	tax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L0024
	dex
L0024:	jsr     asrax2
	clc
	adc     sreg
	bcc     L0070
	inx
L0070:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L0023
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     M0008
	ldy     #$13
	sta     (ptr1),y
	iny
	lda     M0008+1
	bra     L0084
L0023:	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     ptr1
	ldx     #$00
	lda     M0007+1
	bpl     L0027
	dex
L0027:	jsr     asrax2
	clc
	adc     ptr1
	bcc     L0071
	inx
L0071:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L0026
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     M0007
	ldy     #$11
	sta     (ptr1),y
	iny
	lda     M0007+1
L0084:	sta     (ptr1),y
L0026:	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     sreg
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L0029
	dex
L0029:	jsr     asrax2
	clc
	adc     sreg
	bcc     L0072
	inx
L0072:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L0028
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     M0009
	ldy     #$15
	sta     (ptr1),y
	iny
	lda     M0009+1
	sta     (ptr1),y
L0028:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	jeq     L002A
	lda     #$04
	sta     M0006
	stz     M0006+1
L002B:	lda     M0006
	cmp     #$18
	lda     M0006+1
	sbc     #$00
	bvc     L002F
	eor     #$80
L002F:	jpl     L002C
	lda     _g_vehicles
	ldx     _g_vehicles+1
	jsr     pushax
	lda     M0006
	ldx     M0006+1
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L002D
	lda     _g_vehicles
	ldx     _g_vehicles+1
	jsr     pushax
	lda     M0006
	ldx     M0006+1
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	jsr     tosaddax
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     pushax
	ldx     #$00
	lda     #$23
	jsr     _memcpy
	lda     _g_vehicles
	ldx     _g_vehicles+1
	jsr     pushax
	lda     M0006
	ldx     M0006+1
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	jsr     tosaddax
	clc
	adc     #$1D
	bcc     L0032
	inx
L0032:	sta     sreg
	stx     sreg+1
	lda     M0001
	ldx     M0001+1
	clc
	adc     #$1D
	bcc     L007B
	inx
	clc
L007B:	adc     #$04
	bcc     L0034
	inx
L0034:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	sta     (sreg)
	ldy     #$01
	txa
	sta     (sreg),y
	lda     #$00
	jsr     _AddSound
	bra     L002C
L002D:	inc     M0006
	jne     L002B
	inc     M0006+1
	jmp     L002B
L002C:	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     #$00
	ldy     #$03
	sta     (ptr1),y
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     #$05
	ldy     #$0B
	bra     L007A
L002A:	lda     M0001
	ldx     M0001+1
	ldy     #$0B
	jsr     ldaidx
	beq     L0036
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     (ptr1),y
	sec
	sbc     #$01
L007A:	sta     (ptr1),y
L0036:	lda     M0001
	ldx     M0001+1
	ldy     #$08
	jsr     ldaidx
	beq     L0004
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
L0004:	inc     M0005
	bne     L0007
	inc     M0005+1
L0007:	lda     #$23
	clc
	adc     M0001
	sta     M0001
	jcc     L0002
	inc     M0001+1
	jmp     L0002
L0003:	lda     _g_vehicles
	ldx     _g_vehicles+1
	jsr     pushax
	lda     M0005
	ldx     M0005+1
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	jsr     tosaddax
	sta     M0002
	stx     M0002+1
L0038:	lda     M0005
	cmp     #$18
	lda     M0005+1
	sbc     #$00
	bvc     L003C
	eor     #$80
L003C:	bmi     L00B7
	rts
L00B7:	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	beq     L003F
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     #$00
	sta     (ptr1)
L003F:	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     (ptr1)
	jeq     L003A
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     sreg
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L0041
	dex
L0041:	jsr     asrax2
	clc
	adc     sreg
	bcc     L0073
	inx
L0073:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     M0009+1
	lda     (ptr1)
	sta     M0009
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$16
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	cmp     M0009
	txa
	sbc     M0009+1
	bvc     L0074
	eor     #$80
L0074:	bpl     L0042
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     #$01
	ldy     #$02
	sta     (ptr1),y
L0042:	lda     M0002
	ldx     M0002+1
	ldy     #$0C
	jsr     ldaidx
	beq     L0043
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
	jsr     bnega
	beq     L0043
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     #$01
	ldy     #$02
	sta     (ptr1),y
L0043:	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$12
	lda     (ptr1),y
	sta     M0007+1
	dey
	lda     (ptr1),y
	sta     M0007
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	sta     M0008+1
	dey
	lda     (ptr1),y
	sta     M0008
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$16
	lda     (ptr1),y
	sta     M0009+1
	dey
	lda     (ptr1),y
	sta     M0009
	lda     M0002
	ldx     M0002+1
	ldy     #$05
	jsr     ldaidx
	jeq     L0047
	lda     M0002
	ldx     M0002+1
	sta     ptr2
	stx     ptr2+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$18
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     sreg
	stx     sreg+1
	lda     M0002
	ldx     M0002+1
	ldy     #$05
	jsr     ldaidx
	jsr     aslax2
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	ldy     #$17
	sta     (ptr2),y
	iny
	txa
	sta     (ptr2),y
	lda     M0002
	ldx     M0002+1
	jsr     pushax
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$18
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _Sin
	ldy     #$19
	jsr     staxspidx
	lda     M0002
	ldx     M0002+1
	jsr     pushax
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$18
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _Cos
	ldy     #$1B
	jsr     staxspidx
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     #$00
	ldy     #$05
	sta     (ptr1),y
L0047:	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$1A
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax3
	clc
	adc     M0007
	sta     M0007
	txa
	adc     M0007+1
	sta     M0007+1
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$1C
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax3
	clc
	adc     M0008
	sta     M0008
	txa
	adc     M0008+1
	sta     M0008+1
	lda     M0007
	ldx     M0007+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     _Maximum
	jsr     pushax
	ldx     #$3F
	lda     #$FF
	jsr     _Minimum
	sta     M0007
	stx     M0007+1
	lda     M0008
	ldx     M0008+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     _Maximum
	jsr     pushax
	ldx     #$3F
	lda     #$FF
	jsr     _Minimum
	sta     M0008
	stx     M0008+1
	lda     M0002
	ldx     M0002+1
	ldy     #$04
	jsr     ldaidx
	beq     L0048
	lda     M0002
	ldx     M0002+1
	jsr     ldaidx
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0009
	sta     M0009
	lda     tmp1
	adc     M0009+1
	sta     M0009+1
	lda     M0009
	ldx     M0009+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     _Maximum
	jsr     pushax
	ldx     #$3F
	lda     #$FF
	jsr     _Minimum
	sta     M0009
	stx     M0009+1
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
L0048:	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0008
	ldx     M0008+1
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     ptr1
	ldx     #$00
	lda     M0007+1
	bpl     L004A
	dex
L004A:	jsr     asrax2
	clc
	adc     ptr1
	bcc     L0075
	inx
L0075:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L0049
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     M0007
	ldy     #$11
	sta     (ptr1),y
	iny
	lda     M0007+1
	sta     (ptr1),y
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     M0008
	iny
	sta     (ptr1),y
	iny
	lda     M0008+1
	jmp     L0085
L0049:	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0008
	ldx     M0008+1
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     sreg
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$12
	lda     (ptr1),y
	tax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L004D
	dex
L004D:	jsr     asrax2
	clc
	adc     sreg
	bcc     L0076
	inx
L0076:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L004C
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     M0008
	ldy     #$13
	sta     (ptr1),y
	iny
	lda     M0008+1
	bra     L0085
L004C:	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     ptr1
	ldx     #$00
	lda     M0007+1
	bpl     L0050
	dex
L0050:	jsr     asrax2
	clc
	adc     ptr1
	bcc     L0077
	inx
L0077:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L004F
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     M0007
	ldy     #$11
	sta     (ptr1),y
	iny
	lda     M0007+1
	bra     L0085
L004F:	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     #$01
	ldy     #$02
L0085:	sta     (ptr1),y
	lda     M0009
	ldx     M0009+1
	jsr     pushax
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     asrax4
	jsr     asrax2
	and     #$F0
	sta     sreg
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L0053
	dex
L0053:	jsr     asrax2
	clc
	adc     sreg
	bcc     L0078
	inx
L0078:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     M0004
	sta     ptr1
	lda     tmp1
	adc     M0004+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     tosicmp
	bmi     L0052
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	lda     M0009
	ldy     #$15
	sta     (ptr1),y
	iny
	lda     M0009+1
	sta     (ptr1),y
L0052:	stz     M0006
	stz     M0006+1
L0054:	lda     M0006
	cmp     #$04
	lda     M0006+1
	sbc     #$00
	bvc     L0058
	eor     #$80
L0058:	jpl     L0055
	lda     _g_vehicles
	ldx     _g_vehicles+1
	jsr     pushax
	lda     M0006
	ldx     M0006+1
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	jsr     tosaddax
	sta     M0001
	stx     M0001+1
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$0E
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$0E
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosicmp
	jeq     L0056
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     (ptr1)
	jeq     L0056
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$16
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$16
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tossubax
	jsr     _abs
	cmp     #$C0
	txa
	sbc     #$00
	bvc     L005C
	eor     #$80
L005C:	jpl     L0056
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$12
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$12
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tossubax
	jsr     _abs
	jsr     asrax2
	sta     M000A
	stx     M000A+1
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$14
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tossubax
	jsr     _abs
	jsr     asrax2
	sta     M000B
	stx     M000B+1
	lda     M000A
	cmp     #$73
	lda     M000A+1
	sbc     #$00
	bvc     L0060
	eor     #$80
L0060:	jpl     L0056
	lda     M000B
	cmp     #$73
	lda     M000B+1
	sbc     #$00
	bvc     L0062
	eor     #$80
L0062:	jpl     L0056
	lda     M000A
	ldx     M000A+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     _g_squares
	sta     ptr1
	lda     tmp1
	adc     _g_squares+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	sta     sreg
	stx     sreg+1
	lda     M000B
	ldx     M000B+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     _g_squares
	sta     ptr1
	lda     tmp1
	adc     _g_squares+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	cpx     #$33
	bne     L0063
	cmp     #$A9
L0063:	jcs     L0056
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	tya
	iny
	sta     (ptr1),y
	lda     M0001
	ldx     M0001+1
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$10
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	lda     M0002
	ldx     M0002+1
	ldy     #$0A
	jsr     ldaidx
	jsr     tossubax
	ldy     #$0F
	jsr     staxspidx
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	lda     #$03
	ldy     #$08
	sta     (ptr1),y
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	ldy     #$10
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	cmp     #$01
	txa
	sbc     #$00
	bvc     L0067
	eor     #$80
L0067:	bpl     L0056
	lda     _g_vehicles
	ldx     _g_vehicles+1
	jsr     pushax
	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$0E
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	jsr     tosaddax
	jsr     _AdvancePlayer
	lda     M0001
	ldx     M0001+1
	jsr     _AdvancePlayer
	tax
	bne     L0056
	lda     M0001+1
	sta     ptr1+1
	lda     M0001
	sta     ptr1
	txa
	sta     (ptr1)
L0056:	inc     M0006
	jne     L0054
	inc     M0006+1
	jmp     L0054
L0055:	lda     M0002+1
	sta     ptr1+1
	lda     M0002
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	beq     L003A
	lda     M0002
	ldx     M0002+1
	clc
	adc     #$1D
	bcc     L006A
	inx
L006A:	sta     ptr1
	stx     ptr1+1
	lda     _g_exploding_prm
	sta     (ptr1)
	dey
	lda     _g_exploding_prm+1
	sta     (ptr1),y
	lda     M0002
	ldx     M0002+1
	clc
	adc     #$1D
	bcc     L007C
	inx
	clc
L007C:	adc     #$02
	bcc     L006C
	inx
L006C:	sta     ptr1
	stx     ptr1+1
	lda     _g_exploding_aux
	sta     (ptr1)
	ldy     #$01
	lda     _g_exploding_aux+1
	sta     (ptr1),y
	tya
	jsr     _AddSound
L003A:	inc     M0005
	bne     L003D
	inc     M0005+1
L003D:	lda     #$23
	clc
	adc     M0002
	sta     M0002
	jcc     L0038
	inc     M0002+1
	jmp     L0038

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00
M0003:
	.res	1,$00
M0004:
	.res	2,$00
M0005:
	.res	2,$00
M0006:
	.res	2,$00
M0007:
	.res	2,$00
M0008:
	.res	2,$00
M0009:
	.res	2,$00
M000A:
	.res	2,$00
M000B:
	.res	2,$00

.endproc

